### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by 7YSE** [tobiichiamane/pixivcs#5]
您如何实现在PixivPy中实现的下载功能？

**Comment by tobiichiamane** [comment]
参考[此方法](https://github.com/tobiichiamane/pixivfs-uwp/blob/f83e02fa98ca7da498ab1b61914a5f011fa08762/PixivFSUWP/Data/OverAll.cs#L86)

**Comment by 7YSE** [comment]
对于延迟的回复，我们深表歉意。
谢谢您的回答。
